import { Activity, ArrowRight, CheckCircle2, Clock3, HeartHandshake, Mail, MapPin, MonitorCheck, Phone, ShieldCheck, Sparkles, Stethoscope } from "lucide-react";
import { Link } from "react-router-dom";

const PageHero = ({ eyebrow, title, text, position = "center" }) => <section className={`info-hero image-${position}`}><div className="info-hero-overlay"/><div className="public-container"><p className="public-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div></section>;
const CTA = () => <section className="public-cta"><div><p className="public-eyebrow dark">Patient support</p><h2>Questions about treatment or your visit?</h2></div><Link to="/contact" className="public-primary">Talk to our team <ArrowRight size={17}/></Link></section>;

export const AboutPage = () => <><PageHero eyebrow="About Emmanuel Hospital" title="Rooted in care. Focused on better outcomes." text="Since 2009, our dialysis center has supported patients and families with attentive, dependable renal care." position="right"/><section className="public-section"><div className="public-container public-split"><div><p className="public-eyebrow dark">Our purpose</p><h2>Care that sees the person, not just the treatment.</h2></div><div><p>We believe excellent dialysis care balances clinical discipline with kindness. Every treatment plan, conversation, and space is shaped to help patients feel informed, respected, and supported.</p><p>Our team works together to create consistent experiences and maintain the continuity that long-term care deserves.</p></div></div><div className="public-container public-values"><article><HeartHandshake/><h3>Compassion</h3><p>We listen closely and care with patience.</p></article><article><ShieldCheck/><h3>Integrity</h3><p>We act responsibly and communicate clearly.</p></article><article><Sparkles/><h3>Excellence</h3><p>We continuously strengthen care and service.</p></article></div></section><CTA/></>;

export const ServicesPage = () => <><PageHero eyebrow="Dialysis services" title="Coordinated care for every stage of treatment." text="Patient-focused services designed to make treatment safer, clearer, and easier to navigate."/><section className="public-section public-muted"><div className="public-container"><div className="public-section-heading"><div><p className="public-eyebrow dark">What we provide</p><h2>Support beyond the dialysis station.</h2></div></div><div className="service-list"><article><span>01</span><div><Stethoscope/><h3>Hemodialysis treatment</h3><p>Scheduled center-based treatment with ongoing clinical observation and attentive support.</p></div></article><article><span>02</span><div><Activity/><h3>Treatment monitoring</h3><p>Organized session records and monitoring help the care team maintain continuity across visits.</p></div></article><article><span>03</span><div><HeartHandshake/><h3>Patient coordination</h3><p>Clear guidance helps patients and families understand schedules, documentation, and care needs.</p></div></article></div></div></section><CTA/></>;

export const TechnologyPage = () => <><PageHero eyebrow="Facilities & technology" title="Modern systems. Calm, carefully designed spaces." text="Technology supports precision, while thoughtful facilities support the person receiving care." position="left"/><section className="public-section"><div className="public-container technology-grid"><div className="technology-image"/><div><p className="public-eyebrow dark">Treatment environment</p><h2>Built for safety, visibility, and comfort.</h2><p>Our dialysis stations bring essential treatment and monitoring tools together in a bright, organized environment.</p><ul><li><MonitorCheck/> Modern treatment monitoring</li><li><ShieldCheck/> Structured clinical workflows</li><li><CheckCircle2/> Comfortable patient stations</li><li><Sparkles/> Clean, thoughtfully maintained spaces</li></ul></div></div></section><CTA/></>;

export const ContactPage = () => <><PageHero eyebrow="Contact & visits" title="We are ready to help you plan your next step." text="Reach the center for treatment inquiries, scheduling guidance, or help accessing the secure portal." position="right"/><section className="public-section"><div className="public-container contact-grid"><div><p className="public-eyebrow dark">Get in touch</p><h2>Talk with our care team.</h2><p>Use the confirmed contact details provided by the center for appointments and patient inquiries.</p><div className="contact-cards"><article><Phone/><div><strong>Call the center</strong><span>For scheduling and treatment questions</span></div></article><article><Mail/><div><strong>Email support</strong><span>For general and portal inquiries</span></div></article><article><MapPin/><div><strong>Visit us</strong><span>Emmanuel Hospital Dialysis Center</span></div></article><article><Clock3/><div><strong>Center hours</strong><span>Contact the center for the current schedule</span></div></article></div></div><aside><h3>Already registered?</h3><p>Access records, messages, alerts, and role-specific tools through the secure portal.</p><Link to="/login" className="public-primary">Sign in to portal <ArrowRight size={17}/></Link><small>Do not share your password or account ID with anyone.</small></aside></div></section></>;
